<?php

namespace AppBundle\Repository;

/**
 * PasscodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PasscodeRepository extends \Doctrine\ORM\EntityRepository
{
}
