<?php

namespace AccountingBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RateRepository extends EntityRepository
{
    public function getByDate($date)
    {

        $monthFrom = new \DateTime($date);
        $newDate = new \DateTime($date);
        $monthTo =  $newDate->modify('+1 month')->format('Y-m');

        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('c')
            ->from('AccountingBundle:Rate', 'c')
            ->where('c.dateInsert BETWEEN :firstDate AND :lastDate')
            ->setParameter('firstDate', $monthFrom)
            ->setParameter('lastDate', $monthTo)
        ;

        $result = $qb->getQuery()->getResult();

        return $result;
    }
}
